name:                poroscope
version:             0.1.0.0
github:              "keuhdall/poroscope"
license:             BSD3
author:              "keuhdall"
maintainer:          "keuhdall@gmail.com"
copyright:           "2021 keuhdall"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/keuhdall/poroscope#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- hasql
- uuid
- bytestring
- text

library:
  source-dirs: src

executables:
  poroscope-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poroscope

tests:
  poroscope-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poroscope
